version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: minexora
      POSTGRES_PASSWORD: "deneme12"
      POSTGRES_DB: library
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432